# File-level variables
@baseUrl = https://jsonplaceholder.typicode.com
@userId = 1

### Test file variables
# @name testFileVars
GET {{baseUrl}}/users/{{userId}}

### Test system variables
# @name testSystemVars
GET https://httpbin.org/anything
X-Timestamp: {{$timestamp}}
X-UUID: {{$uuid}}
X-RandomInt: {{$randomInt 1 100}}
